### ISSUE TITLE
Exeption parsing hub names

### ISSUE THREAD

**Issue by jimboca** [jimboca/udi-harmony-poly#27]
```
2020-12-04 08:15:22,031 Thread-1   polyinterface      INFO     HarmonyController:l_info: HarmonyController:_set_num_hubs: 0
2020-12-04 08:15:22,032 Thread-1   polyinterface      INFO     polyinterface:reportDriver: Updating Driver harmonyctrl - GV7: 2, uom: 25
2020-12-04 08:15:22,034 Thread-1   polyinterface      INFO     HarmonyController:l_info: HarmonyController:discover: harmony_discover: starting...
2020-12-04 08:15:22,037 Thread-1   polyinterface      DEBUG    discovery:get_network_interface: gateway: default=('192.168.71.1', 'igb0')
2020-12-04 08:15:22,038 Thread-1   polyinterface      DEBUG    discovery:get_network_interface: gateway->ifad: igb0=[{'addr': '192.168.71.23', 'netmask': '255.255.255.0', 'broadcast': '192.168.71.255'}]
2020-12-04 08:15:22,039 Thread-1   polyinterface      INFO     discovery:get_network_bcast: get_network_bcast: Returning 192.168.71.255
2020-12-04 08:15:22,042 Thread-1   polyinterface      DEBUG    discovery:discover: Pinging network 192.168.71.255 port 61991
2020-12-04 08:15:23,046 Thread-1   polyinterface      DEBUG    discovery:discover: Pinging network 192.168.71.255 port 61991
2020-12-04 08:15:24,056 Thread-1   polyinterface      DEBUG    discovery:discover: Pinging network 192.168.71.255 port 61991
2020-12-04 08:15:25,086 Thread-1   polyinterface      DEBUG    discovery:discover: Pinging network 192.168.71.255 port 61991
2020-12-04 08:15:25,665 Controller polyinterface      DEBUG    HarmonyController:canPoll: discover thread still running...
2020-12-04 08:15:26,109 Thread-1   polyinterface      DEBUG    discovery:discover: Pinging network 192.168.71.255 port 61991
2020-12-04 08:15:27,116 Thread-1   polyinterface      DEBUG    discovery:discover: Pinging network 192.168.71.255 port 61991
2020-12-04 08:15:28,154 Thread-1   polyinterface      DEBUG    discovery:discover: Pinging network 192.168.71.255 port 61991
2020-12-04 08:15:29,177 Thread-1   polyinterface      DEBUG    discovery:discover: Pinging network 192.168.71.255 port 61991
2020-12-04 08:15:30,178 Thread-1   polyinterface      DEBUG    discovery:discover: Pinging network 192.168.71.255 port 61991
2020-12-04 08:15:30,672 Controller polyinterface      DEBUG    HarmonyController:canPoll: discover thread still running...
2020-12-04 08:15:31,181 Thread-1   polyinterface      DEBUG    discovery:discover: Pinging network 192.168.71.255 port 61991
2020-12-04 08:15:32,185 Thread-2   polyinterface      INFO     discovery:listen: Listen socket already closed? [Errno 53] Software caused connection abort
2020-12-04 08:15:32,186 Thread-1   polyinterface      INFO     discovery:discover: Completed scan, 0 hub(s) found.
2020-12-04 08:15:32,188 Thread-1   polyinterface      INFO     HarmonyController:l_info: HarmonyController:discover: harmony_discover: []
2020-12-04 08:15:32,188 Thread-1   polyinterface      INFO     polyinterface:reportDriver: Updating Driver harmonyctrl - GV7: 3, uom: 25
2020-12-04 08:15:32,192 Thread-1   polyinterface      INFO     HarmonyController:l_info: HarmonyController:discover: param=hub_62 match=<re.Match object; span=(0, 6), match='hub_62'>
2020-12-04 08:15:32,193 Thread-1   polyinterface      INFO     HarmonyController:l_info: HarmonyController:discover: process param=hub_62 address=62
2020-12-04 08:15:32,197 Thread-1   polyinterface      INFO     HarmonyController:l_info: HarmonyController:discover: param=hub_61 match=<re.Match object; span=(0, 6), match='hub_61'>
2020-12-04 08:15:32,198 Thread-1   polyinterface      INFO     HarmonyController:l_info: HarmonyController:discover: process param=hub_61 address=61
2020-12-04 08:15:32,210 Thread-1   polyinterface      ERROR    polyinterface:write: Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/polyglot/nodeservers/HarmonyHub/harmony_hub_nodes/HarmonyController.py", line 289, in _discover
    index = next((idx for (idx, hub) in enumerate(self.hubs) if hub['name'] == hub_name), None)
  File "/var/polyglot/nodeservers/HarmonyHub/harmony_hub_nodes/HarmonyController.py", line 289, in <genexpr>
    index = next((idx for (idx, hub) in enumerate(self.hubs) if hub['name'] == hub_name), None)
NameError: free variable 'hub_name' referenced before assignment in enclosing scope
2020-12-04 08:15:35,682 Controller polyinterface      DEBUG    HarmonyController:canPoll: discover thread is done...
```

**Comment by jimboca** [comment]
Should be fixed in 2.2.4
