### ISSUE TITLE
HarmonyHub on Polisy for ISY

### ISSUE THREAD

**Issue by timwing** [jimboca/udi-harmony-poly#28]
I just installed HarmonyHub 2.4.3 on my Universal Devices Polisy and I am having issues getting it to start.

The hub has a static ip & I have enabled XMPP in the Harmony app. Below is the Log from Polisy when trying to start the node. What am I missing?
```
2020-12-05 10:38:10,766 MainThread polyinterface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2020-12-05 10:38:11,809 MainThread polyinterface      INFO     polyinterface:init_interface: Received Config from STDIN.
2020-12-05 10:38:11,810 MainThread polyinterface      INFO     __init__:<module>: UDI Polyglot v2 Interface 2.1.0 Starting...
2020-12-05 10:38:11,997 MainThread polyinterface      ERROR    polyinterface:write: Traceback (most recent call last):
2020-12-05 10:38:11,998 MainThread polyinterface      ERROR    polyinterface:write: File "./harmony_hub.py", line 13, in <module>
2020-12-05 10:38:11,999 MainThread polyinterface      ERROR    polyinterface:write: from harmony_hub_nodes import HarmonyController
2020-12-05 10:38:12,000 MainThread polyinterface      ERROR    polyinterface:write: File "/var/polyglot/nodeservers/HarmonyHub/harmony_hub_nodes/__init__.py", line 7, in <module>
2020-12-05 10:38:12,001 MainThread polyinterface      ERROR    polyinterface:write: from .HarmonyHub import HarmonyHub
2020-12-05 10:38:12,002 MainThread polyinterface      ERROR    polyinterface:write: File "/var/polyglot/nodeservers/HarmonyHub/harmony_hub_nodes/HarmonyHub.py", line 6, in <module>
2020-12-05 10:38:12,003 MainThread polyinterface      ERROR    polyinterface:write: from harmony_hub_funcs import ip2long,long2ip,get_valid_node_name,get_file
2020-12-05 10:38:12,004 MainThread polyinterface      ERROR    polyinterface:write: File "/var/polyglot/nodeservers/HarmonyHub/harmony_hub_funcs.py", line 5, in <module>
2020-12-05 10:38:12,005 MainThread polyinterface      ERROR    polyinterface:write: from pyharmony import ha_get_client
2020-12-05 10:38:12,006 MainThread polyinterface      ERROR    polyinterface:write: ModuleNotFoundError
2020-12-05 10:38:12,006 MainThread polyinterface      ERROR    polyinterface:write: :
2020-12-05 10:38:12,007 MainThread polyinterface      ERROR    polyinterface:write: No module named 'pyharmony'
```

**Comment by jimboca** [comment]
It looks like Polyglot install of the nodeserver failed, if you can log into your Polisy and run the install.sh manually?
```
ssh admin@polisy
cd /var/polyglot/nodeservers/HarmonyHub
sudo -u polyglot ./install.sh
```
Let me know how that goes.

**Comment by timwing** [comment]
This is what I got...

login as: admin
Keyboard-interactive authentication prompts from server:
| Password for admin@polisy:
End of keyboard-interactive prompts from server
Last login: Sat Dec  5 14:11:32 2020 from shoppc.localdomain
FreeBSD 12.1-RELEASE-p1 r355229 POLISY

Welcome to Polisy!
[admin@polisy ~]$ cd /var/polyglot/nodeservers/HarmonyHub
[admin@polisy /var/polyglot/nodeservers/HarmonyHub]$ sudo -u polyglot ./install.sh
Password:
Using: requirements_polisy.txt
ld-elf.so.1: /usr/local/lib/libpython3.7m.so.1.0: Undefined symbol "close_range@FBSD_1.6"
Requirement already satisfied: polyinterface>=2.0.40 in /var/polyglot/.local/lib/python3.7/site-packages (from -r requirements_polisy.txt (line 1)) (2.1.0)
Collecting pyaml
  Using cached pyaml-20.4.0-py2.py3-none-any.whl (17 kB)
Collecting sleekxmpp
  Using cached sleekxmpp-1.3.3.tar.gz (845 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wx3zo30m/sleekxmpp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wx3zo30m/sleekxmpp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rp5yfv5x
         cwd: /tmp/pip-install-wx3zo30m/sleekxmpp/
    Complete output (1 lines):
    ld-elf.so.1: /usr/local/lib/libpython3.7m.so.1.0: Undefined symbol "close_range@FBSD_1.6"
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: pip3 failed, see above
[admin@polisy /var/polyglot/nodeservers/HarmonyHub]$

**Comment by jimboca** [comment]
This is an issue others have seen after a polisy update. Please send a
ticket to udi support that you are getting this error and they will help
ld-elf.so.1: /usr/local/lib/libpython3.7m.so.1.0: Undefined symbol
"close_range@FBSD_1.6"

**Comment by timwing** [comment]
Will do jimboca. Thank you for your help.
