### ISSUE TITLE
Issue when clicking on Discovery for custom params

### ISSUE THREAD

**Issue by therealmysteryman** [jimboca/udi-harmony-poly#6]
I  added manually the param since the Harmony Hub doesn't get auto-discover

Key : hub_172165031
{ "name":"HarmonyHub Sous-Sol", "host":"172.16.50.31" }

Once I start the Polyglot Server and click Discover the Polyglot crash here the stack trace :

2018-1-20 22:49:26 - info: HarmonyHub(7): harmonyctrl GV7 set sucessfully to 2
2018-1-20 22:49:36 - error: NSChild: HarmonyHub STDERR: Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 542, in _parseInput
    self.nodes[input[key]['address']].runCmd(input[key])
  File "/root/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 450, in runCmd
    fun(self, command)
  File "/root/.polyglot/nodeservers/HarmonyHub/harmony_hub_nodes/HarmonyController.py", line 351, in _cmd_discover
    self.discover()
  File "/root/.polyglot/nodeservers/HarmonyHub/harmony_hub_nodes/HarmonyController.py", line 208, in discover
    if addIt:
NameError: name 'addIt' is not defined

**Comment by jimboca** [comment]
Sorry I'll take a look. This used to work but obviously I haven't tested it recently.

**Comment by jimboca** [comment]
This should be fixed.  Upgrade the nodeserver in the store, you can click 'Cancel' since it doesn't need to upload a new profile.  Then restart the nodeserver and try discover again.

**Comment by therealmysteryman** [comment]
that solved the issue thanks :)

**Comment by jimboca** [comment]
Awesome, thanks for the report
