### ISSUE TITLE
Turning on an Activity is busted

### ISSUE THREAD

**Issue by jimboca** [jimboca/udi-harmony-poly#7]
```
2018-02-01 13:02:16,128 DEBUG    Activity:a28066022:Xbox one:_set_st: set=0, get=0
 

2018-02-01 13:02:43,936 DEBUG Activity:a28066022:Xbox one:_cmd_on:
2018-02-01 13:02:43,939 ERROR Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/home/tom/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 602, in _parseInput
self.nodes[input[key]['address']].runCmd(input[key])
File "/home/tom/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 510, in runCmd
fun(self, command)
File "/home/tom/.polyglot/nodeservers/HarmonyHub/harmony_hub_nodes/HarmonyActivity.py", line 74, in _cmd_on
ret = self.primary.start_activity(id=self.number)
AttributeError: 'str' object has no attribute 'start_activity'
```

**Comment by jimboca** [comment]
Fixed in 2.1.6
