### ISSUE TITLE
Need to catch all timeouts

### ISSUE THREAD

**Issue by jimboca** [jimboca/udi-harmony-poly#8]
```
2018-02-28 07:35:13,520 ERROR    Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/pyharmony/client.py", line 180, in change_channel
    result = iq_cmd.send(block=True)
  File "/home/pi/.local/lib/python3.5/site-packages/sleekxmpp/stanza/iq.py", line 233, in send
    raise IqTimeout(self)
sleekxmpp.exceptions.IqTimeout: <iq id="632bcd17-67b5-465d-8407-695d83c28146-8" type="get"><oa mime="harmony.engine?changeChannel" xmlns="connect.logitech.com">channel=1046:timestamp=0</oa></iq>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 603, in _parseInput
    self.nodes[input[key]['address']].runCmd(input[key])
  File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 510, in runCmd
    fun(self, command)
  File "/home/pi/development/udi-harmony-poly/harmony_hub_nodes/HarmonyHub.py", line 372, in _cmd_change_channel
    return self.change_channel(channel)
  File "/home/pi/development/udi-harmony-poly/harmony_hub_nodes/HarmonyHub.py", line 353, in change_channel
    ret = self.client.change_channel(channel)
  File "/home/pi/.local/lib/python3.5/site-packages/pyharmony/client.py", line 183, in change_channel
    result = iq_cmd.send(block=True)
  File "/home/pi/.local/lib/python3.5/site-packages/sleekxmpp/stanza/iq.py", line 233, in send
    raise IqTimeout(self)
sleekxmpp.exceptions.IqTimeout: <iq id="632bcd17-67b5-465d-8407-695d83c28146-8" type="get"><oa mime="harmony.engine?changeChannel" xmlns="connect.logitech.com">channel=1046:timestamp=0</oa></iq>
```

**Comment by jimboca** [comment]
Fixed
